### ISSUE TITLE
What is the purpose of the login/logout handlers?

### ISSUE THREAD

**Issue by thkoch2001** [codeconsortium/CCDNUserSecurityBundle#29]
The LoginFailureHandler adds the failed login attempts to the cc_security_session table. But couldn't that be done in a listener?

And the redirection logic in all the handlers, isn't this a code duplication with what is already provided by Symfony? Plain Symfony already provides means to redirect the user to the last seen page before the login attempt.

**Comment by romaricdrigon** [comment]
I came across the same conclusion, even worse I needed the flexibility of the original listeners.

So here is #45! Now that the bundle require Symfony 2.5+ here should be no issues.

**Comment by ahmadnazir** [comment]
This should be closed as PR #45 from @romaricdrigon has been merged. Is there any reason why this is still open?
