### ISSUE TITLE
update to support symfony 2.5

### ISSUE THREAD

**Issue by thkoch2001** [codeconsortium/CCDNUserSecurityBundle#30]
The dependencies defined for this bundle have an upper bound on the supported Symfony version. It should however work without changes with symfony 2.5 too. I've seen no backwards incompatible chanes from 2.4 to 2.5 that should affect this bundle.

**Comment by ricbra** [comment]
This is fixed in https://github.com/codeconsortium/CCDNUserSecurityBundle/pull/39

**Comment by potherca** [comment]
If it is fixed, should this issue not be closed:question:

**Comment by ricbra** [comment]
As I'm not the maintainer I unfortunately cannot close this issue. It should be closed indeed :smile:
