### ISSUE TITLE
Symfony 2.7 ready?

### ISSUE THREAD

**Issue by diimpp** [codeconsortium/CCDNUserSecurityBundle#46]
Hi,

Symfony 2.7 was just released and bundle have <2.7 constraint.

Regards.

**Comment by diimpp** [comment]
I've started to use it from my fork without <2.7 constraint and it works fine. Didn't test in details though.

**Comment by bertoost** [comment]
Please merge! :-) since Symfony 2.6 had it's last update
http://symfony.com/blog/symfony-2-6-11-released

**Comment by jrojat** [comment]
+1 please merge for symfony 2.7

**Comment by SchizoDuckie** [comment]
+1 please merge

**Comment by FR33D0M5K135** [comment]
+1 please merge

**Comment by grizzlylab** [comment]
+1 please merge. My fork is working fine with symfony 2.7!

**Comment by benr77** [comment]
+1 agreed please merge thanks

**Comment by FrancoisMartin** [comment]
+1 please merge !

**Comment by npotier** [comment]
+1. Do you need help on this ?

**Comment by yahuarkuntur** [comment]
+1 please merge !

**Comment by ricbra** [comment]
+1

**Comment by krizon** [comment]
+1
